### ISSUE TITLE
'NoneType' object has no attribute 'reader'

### ISSUE THREAD

**Issue by AMhadhbi** [RomMarwa/AddressVerification#1]
Hi @RomMarwa  

Thank you for your sharing the code 

There is an issue when I add address and confirm.

please check it 

Traceback (most recent call last):
  File "/var/www/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/var/www/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/var/www/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/var/www/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/var/www/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/var/www/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/www/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/www/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/var/www/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/var/www/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/var/www/addons/website_sale/controllers/main.py", line 581, in address
    errors, error_msg = self.checkout_form_validate(mode, kw, pre_values)
  File "/var/www/addons/website_address_verification/controllers/main.py", line 71, in checkout_form_validate
    address_error, zip_code_is_valid = self.search_zipCode_cities(country_code, zip_code, city)
  File "/var/www/addons/website_address_verification/controllers/main.py", line 45, in search_zipCode_cities
    reader = unicodecsv.reader(data_file, encoding='utf-8', delimiter='	')
AttributeError: 'NoneType' object has no attribute 'reader'

**Comment by RomMarwa** [comment]
Hi Achraf,

I am sorry for the delay,
Please check if unicodecsv python package is installed.
